[package]
name = "ccb-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
console = "0.16.0"
dialoguer = "0.12.0"
git2 = "0.20.2"
log = "0.4.27"
