[package]
name = "ccb-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.16.0"
dialoguer = "0.12.0"
git2 = "0.20.2"
git2_credentials = "0.15.0"
gpgme = "0.11.0"
regex = "1.11.2"

[[bin]]
edition = "2021"
name = "ccb"
path = "src/main.rs"
